services:
  mongo:
    image: mongo:7
    container_name: classpath-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: classpath-back-materiais
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=classpath_materiais
    depends_on:
      - mongo

volumes:
  mongo_data:
